// -----------------------------------------------------------------
// ADMIN MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * AdminAttributes - The complete shape of a Admin record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 */
interface AdminAttributes {
  id: number; // Primary key (auto-generated)
  username: string; // Admin login username
  password: string; // Hashed password
  email: string; // Contact email
  userType: "Admin"; // Role identifier (Admin)
  createdBySuperAdminId: number;
}

/**
 * AdminCreationAttributes - What is needed to create an admin
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'AdminAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating an admin:
 * - id is auto-generated by a database
 * - userType has a default value
 * -
 */
interface AdminCreationAttributes extends Optional<
  AdminAttributes,
  "id" | "userType" | "createdBySuperAdminId"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - Admin model definitions
// -----------------------------------------------------------------
/**
 * The admin class extends Sequelize's model class with the custom types.
 *
 * The generics <AdminAttributes, AdminCreationAttributes> tells Sequelize:
 * - When querying, expect AdminAttribute shape
 * - When creating, allow AdminCreationAttributes shape
 *
 * Implements AdminAttributes ensure the class has all required fields
 */
class Admin
  extends Model<AdminAttributes, AdminCreationAttributes>
  implements AdminAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  public id!: number;
  public username!: string;
  public password!: string;
  public email!: string;
  public userType!: "Admin";
  public createdBySuperAdminId!: number;

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */
  static associate(models: Models) {
    // An admin can have many Posts
    // The foreign key "adminId" will be added to the post table
    Admin.hasMany(models.Post, {
      foreignKey: "adminId",
      onDelete: "CASCADE",
    });

    // An admin can have many Shelters
    Admin.hasMany(models.Shelter, {
      foreignKey: "verifiedByAdminId",
      onDelete: "SET NULL",
    });
    // An admin belongs to one Super Admin
    Admin.belongsTo(models.SuperAdmin, {
      foreignKey: "createdBySuperAdminId",
      onDelete: "SET NULL",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured Admin model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured Admin model class
 */
export default (sequelize: Sequelize) => {
  Admin.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      userType: {
        type: DataTypes.ENUM("Admin"),
        allowNull: false,
        defaultValue: "Admin",
        field: "user_type",
      },
      createdBySuperAdminId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: "created_by_super_admin_id",
        references: { model: "SuperAdmin", key: "id" },
      },
    },
    {
      sequelize,
      modelName: "Admin", // Sequelize internal model name
      tableName: "admins", // Actual database table name
    },
  );
  return Admin;
};
export { Admin };
