import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// ----------------------------------------------
// Admin Model Attribute Definitions
// ----------------------------------------------
// This interface describes ALL fields that exist
// on an Admin record in the database.
// ----------------------------------------------
interface AdminAttributes {
  id: number; // Primary key (auto-generated)
  username: string; // Admin login username
  password: string; // Hashed password
  email: string; // Contact email
  age: number; // Admin age
  userType: "Admin"; // Role identifier (Admin)
  createdBySuperAdminId: number;
}

// ----------------------------------------------
// Creation Attributes
// ----------------------------------------------
// Defines which fields are OPTIONAL when creating
// a new Admin record.
//
// `id` is auto-generated by the database.
// `userType` is assigned a default value.
// ----------------------------------------------
interface AdminCreationAttributes extends Optional<
  AdminAttributes,
  "id" | "userType" | "createdBySuperAdminId"
> {}

// ----------------------------------------------
// Admin Model Class
// ----------------------------------------------
// This class:
// - Maps to the "Admins" database table
// - Provides type-safe access to Admin records
// - Enables Sequelize ORM features
// ----------------------------------------------

class Admin
  extends Model<AdminAttributes, AdminCreationAttributes>
  implements AdminAttributes
{
  public id!: number;
  public username!: string;
  public password!: string;
  public email!: string;
  public age!: number;
  public userType!: "Admin";
  public createdBySuperAdminId!: number;

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // --------------------------------------------
  // Model Associations
  // --------------------------------------------
  // Defines relationships between Admins and
  // other models in the system.
  //
  // - Admin can create many Posts
  // - Admin can manage many Counties
  //
  // Cascade delete ensures related records
  // are removed if an Admin is deleted.
  // --------------------------------------------

  static associate(models: any) {
    Admin.hasMany(models.Post, { onDelete: "cascade" });
    Admin.hasMany(models.County, { onDelete: "cascade" });
    Admin.hasMany(models.Shelter, {
      foreignKey: "verifiedByAdminId",
      onDelete: "SET NULL",
    });
    Admin.belongsTo(models.SuperAdmin, {
      foreignKey: "createdBySuperAdminId",
      onDelete: "SET NULL",
    });
  }
}

// ----------------------------------------------
// Model Initializer
// ----------------------------------------------
// This function:
// - Defines database column types
// - Applies constraints and defaults
// - Registers the model with Sequelize
// ----------------------------------------------
export default (sequelize: Sequelize) => {
  Admin.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      age: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      userType: {
        type: DataTypes.ENUM("Admin"),
        allowNull: false,
        defaultValue: "Admin",
        field: "user_type",
      },
      createdBySuperAdminId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: "created_by_super_admin_id",
        references: { model: "SuperAdmin", key: "id" },
        onDelete: "CASCADE",
      },
    },
    {
      sequelize,
      modelName: "Admin", // Sequelize internal model name
      tableName: "admins", // Actual database table name
    },
  );
  return Admin;
};
