import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// ----------------------------------------------
// Admin Model Attribute Definitions
// ----------------------------------------------
// This interface describes ALL fields that exist
// on an Admin record in the database.
// ----------------------------------------------
interface AdminAttributes {
  id?: number; // Primary key (auto-generated)
  username: string; // Admin login username
  password: string; // Hashed password
  email: string; // Contact email
  age: number; // Admin age
  userType: "Admin"; // Role identifier (Admin)
  created_by_super_admin_id: number;
}

// ----------------------------------------------
// Creation Attributes
// ----------------------------------------------
// Defines which fields are OPTIONAL when creating
// a new Admin record.
//
// `id` is auto-generated by the database.
// `userType` is assigned a default value.
// ----------------------------------------------
interface AdminCreationAttributes extends Optional<
  AdminAttributes,
  "id" | "userType" | "created_by_super_admin_id"
> {}

// ----------------------------------------------
// Admin Model Class
// ----------------------------------------------
// This class:
// - Maps to the "Admins" database table
// - Provides type-safe access to Admin records
// - Enables Sequelize ORM features
// ----------------------------------------------

class Admins
  extends Model<AdminAttributes, AdminCreationAttributes>
  implements AdminAttributes
{
  public id!: number;
  public username!: string;
  public password!: string;
  public email!: string;
  public age!: number;
  public userType!: "Admin";
  public created_by_super_admin_id!: number;

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // --------------------------------------------
  // Model Associations
  // --------------------------------------------
  // Defines relationships between Admins and
  // other models in the system.
  //
  // - Admin can create many Posts
  // - Admin can manage many Counties
  //
  // Cascade delete ensures related records
  // are removed if an Admin is deleted.
  // --------------------------------------------

  static associate(models: any) {
    Admins.hasMany(models.Posts, { onDelete: "cascade" });
    Admins.hasMany(models.County, { onDelete: "cascade" });
    Admins.hasMany(models.Shelters, {
      foreignKey: "verified_by_admin_id",
      onDelete: "SET NULL",
    });
    Admins.belongsTo(models.SuperAdmins, {
      foreignKey: "created_by_super_admin_id",
      onDelete: "SET NULL",
    });
  }
}

// ----------------------------------------------
// Model Initializer
// ----------------------------------------------
// This function:
// - Defines database column types
// - Applies constraints and defaults
// - Registers the model with Sequelize
// ----------------------------------------------
export default (sequelize: Sequelize) => {
  Admins.init(
    {
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      age: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      userType: {
        type: DataTypes.ENUM("Admin"),
        allowNull: false,
        defaultValue: "Admin",
      },
      created_by_super_admin_id: {
        type: DataTypes.INTEGER,
        allowNull: true,
        references: { model: "SuperAdmins", key: "id" },
        onDelete: "CASCADE",
      },
    },
    {
      sequelize,
      modelName: "Admin", // Sequelize internal model name
      tableName: "Admins", // Actual database table name
    },
  );
  return Admins;
};
