import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// ----------------------------------------------
// Adoption Request Model Attribute Definitions
// ----------------------------------------------
// This interface describes ALL fields that exist
// on a adoption request record in the database.
// ----------------------------------------------

interface AdoptionRequestAttributes {
  id: number; // Primary key (auto-generated)
  userId: number; //
  animalId: number; //
  status: "Pending" | "Approved" | "Rejected" | "Cancelled";
  reviewedByStaffId?: number;
  reviewedAt?: Date;
}

// ----------------------------------------------
// Creation Attributes
// ----------------------------------------------
// Defines which fields are OPTIONAL when creating
// a new Adoption Request record.
//
// `id` is auto-generated by the database.
// ----------------------------------------------

interface AdoptionRequestCreationAttributes extends Optional<
  AdoptionRequestAttributes,
  "id" | "status" | "reviewedByStaffId" | "reviewedAt"
> {}

// ----------------------------------------------
// Adoption Request Model Class
// ----------------------------------------------
// This class:
// -
// -
// -
// ----------------------------------------------

class AdoptionRequest
  extends Model<AdoptionRequestAttributes, AdoptionRequestCreationAttributes>
  implements AdoptionRequestAttributes
{
  public id!: number;
  public userId!: number;
  public animalId!: number;
  public status!: "Pending" | "Approved" | "Rejected" | "Cancelled";
  public reviewedByStaffId?: number;
  public reviewedAt?: Date;

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // --------------------------------------------
  // Model Associations
  // --------------------------------------------
  // Defines relationships between Adoption Requests and
  // other models in the system.
  //
  // -
  // -
  //
  // Cascade delete ensures related records
  // are removed if an Admin is deleted.
  // --------------------------------------------

  static associate(models: any) {
    // Each adoption request belongs to ONE user
    AdoptionRequest.belongsTo(models.User, {
      foreignKey: "userId",
      onDelete: "CASCADE",
    });

    // Each adoption request belongs to ONE animal
    AdoptionRequest.belongsTo(models.Animal, {
      foreignKey: "animalId",
      onDelete: "CASCADE",
    });

    // Each adoption request can be reviewed by ONE staff member
    AdoptionRequest.belongsTo(models.ShelterStaff, {
      foreignKey: "reviewedByStaffId",
      onDelete: "SET NULL",
    });
  }
}
// ----------------------------------------------
// Model Initializer
// ----------------------------------------------
// This function:
// - Defines database column types
// - Applies constraints and defaults
// - Registers the model with Sequelize
// ----------------------------------------------
export default (sequelize: Sequelize) => {
  AdoptionRequest.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      userId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "user_id",
        references: { model: "User", key: "id" },
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
      },
      animalId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "animal_id",
        references: { model: "Animal", key: "id" },
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
      },
      status: {
        type: DataTypes.ENUM("Pending", "Approved", "Rejected", "Cancelled"),
        allowNull: false,
        defaultValue: "Pending",
      },
      reviewedByStaffId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: "reviewed_by_staff_id",
        references: { model: "ShelterStaff", key: "id" },
        onDelete: "SET NULL",
      },
      reviewedAt: {
        type: DataTypes.DATE,
        allowNull: true,
        field: "reviewed_at",
      },
    },
    {
      sequelize,
      modelName: "AdoptionRequest", // Sequelize internal model name
      tableName: "adoption_requests", // Actual database table name
    },
  );
  return AdoptionRequest;
};
