import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// ----------------------------------------------
// Adoption Request Model Attribute Definitions
// ----------------------------------------------
// This interface describes ALL fields that exist
// on a adoption request record in the database.
// ----------------------------------------------

interface AdoptionRequestAttributes {
  id?: number; // Primary key (auto-generated)
  user_id: number; //
  animal_id: number; //
  status: "Pending" | "Approved" | "Rejected" | "Cancelled";
  reviewed_by_staff_id?: number;
  reviewed_at?: Date;
}

// ----------------------------------------------
// Creation Attributes
// ----------------------------------------------
// Defines which fields are OPTIONAL when creating
// a new Adoption Request record.
//
// `id` is auto-generated by the database.
// ----------------------------------------------

interface AdoptionRequestCreationAttributes extends Optional<
  AdoptionRequestAttributes,
  "id" | "status" | "reviewed_by_staff_id" | "reviewed_at"
> {}

// ----------------------------------------------
// Adoption Request Model Class
// ----------------------------------------------
// This class:
// -
// -
// -
// ----------------------------------------------

class AdoptionRequest
  extends Model<AdoptionRequestAttributes, AdoptionRequestCreationAttributes>
  implements AdoptionRequestAttributes
{
  public id!: number;
  public user_id!: number;
  public animal_id!: number;
  public status!: "Pending" | "Approved" | "Rejected" | "Cancelled";
  public reviewed_by_staff_id!: number;
  public reviewed_at?: Date | undefined;

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // --------------------------------------------
  // Model Associations
  // --------------------------------------------
  // Defines relationships between Adoption Requests and
  // other models in the system.
  //
  // -
  // -
  //
  // Cascade delete ensures related records
  // are removed if an Admin is deleted.
  // --------------------------------------------

  static associate(models: any) {
    // Each adoption request belongs to ONE user
    AdoptionRequest.belongsTo(models.Users, {
      foreignKey: "user_id",
      onDelete: "CASCADE",
    });

    // Each adoption request belongs to ONE animal
    AdoptionRequest.belongsTo(models.Animals, {
      foreignKey: "animal_id",
      onDelete: "CASCADE",
    });

    // Each adoption request can be reviewed by ONE staff member
    AdoptionRequest.belongsTo(models.ShelterStaff, {
      foreignKey: "reviewed_by_staff_id",
      onDelete: "SET NULL",
    });
  }
}
// ----------------------------------------------
// Model Initializer
// ----------------------------------------------
// This function:
// - Defines database column types
// - Applies constraints and defaults
// - Registers the model with Sequelize
// ----------------------------------------------
export default (sequelize: Sequelize) => {
  AdoptionRequest.init(
    {
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      age: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      userType: {
        type: DataTypes.ENUM("Admin"),
        allowNull: false,
        defaultValue: "Admin",
      },
      created_by_super_admin_id: {
        type: DataTypes.INTEGER,
        allowNull: true,
        references: { model: "SuperAdmins", key: "id" },
        onDelete: "CASCADE",
      },
    },
    {
      sequelize,
      modelName: "Admin", // Sequelize internal model name
      tableName: "Admins", // Actual database table name
    },
  );
  return AdoptionRequest;
};
