// -----------------------------------------------------------------
// ADOPTION REQUEST MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";
import { STATUS } from "./enums/adoptionRequest.enums";
import type { Status } from "./enums/adoptionRequest.enums";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * AdoptionRequestAttributes - The complete shape of a Adoption Request record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 * - Optional fields (with ?) can be null/undefined
 */
interface AdoptionRequestAttributes {
  id: number; // Primary key (auto-generated)
  userId: number; // User requesting adoption
  animalId: number; // Animal being requested
  status: Status; // Pending | Approved | Rejected | Withdrawn
  reviewedByStaffId?: number; // Staff who reviewed the request
  reviewedAt?: Date; // When the review occured
}

/**
 * AdoptionRequestCreationAttributes - What is needed to create an adoption request resource
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'AdoptionRequestAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating an adoption request resource:
 * - id is auto-generated by a database
 * -
 * -
 */

interface AdoptionRequestCreationAttributes extends Optional<
  AdoptionRequestAttributes,
  "id" | "status" | "reviewedByStaffId" | "reviewedAt"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - The adoption request model definitions
// -----------------------------------------------------------------
/**
 * The adoption request class extends Sequelize's model class with the custom types.
 *
 * The generics <AdoptionRequestAttributes, AdoptionRequestCreationAttributes> tells Sequelize:
 * - When querying, expect AdoptionRequestAttribute shape
 * - When creating, allow AdoptionRequestCreationAttributes shape
 *
 * Implements AdoptionRequestAttributes ensure the class has all required fields
 */
class AdoptionRequest
  extends Model<AdoptionRequestAttributes, AdoptionRequestCreationAttributes>
  implements AdoptionRequestAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  // the (?) tells Typescript that this is optional entry
  public id!: number;
  public userId!: number;
  public animalId!: number;
  public status!: Status;
  public reviewedByStaffId?: number;
  public reviewedAt?: Date;

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */

  static associate(models: Models) {
    // Each adoption request belongs to ONE user
    AdoptionRequest.belongsTo(models.User, {
      foreignKey: "userId",
      onDelete: "CASCADE",
    });

    // Each adoption request belongs to ONE animal
    AdoptionRequest.belongsTo(models.Animal, {
      foreignKey: "animalId",
      onDelete: "CASCADE",
    });

    // Each adoption request can be reviewed by ONE staff member
    AdoptionRequest.belongsTo(models.ShelterStaff, {
      foreignKey: "reviewedByStaffId",
      onDelete: "SET NULL",
    });
  }
}
// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured Adoption request model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured adoption requests model class
 */
export default (sequelize: Sequelize) => {
  AdoptionRequest.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      userId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "user_id",
        references: { model: "User", key: "id" },
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
      },
      animalId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "animal_id",
        references: { model: "Animal", key: "id" },
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
      },
      status: {
        type: DataTypes.ENUM(...STATUS),
        allowNull: false,
        defaultValue: "Pending",
      },
      reviewedByStaffId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: "reviewed_by_staff_id",
        references: { model: "ShelterStaff", key: "id" },
        onDelete: "SET NULL",
      },
      reviewedAt: {
        type: DataTypes.DATE,
        allowNull: true,
        field: "reviewed_at",
        validate: {
          isDate: true,
        },
      },
    },
    {
      sequelize,
      modelName: "AdoptionRequest", // Sequelize internal model name
      tableName: "adoption_requests", // Actual database table name
    },
  );
  return AdoptionRequest;
};

export { AdoptionRequest };
