// -----------------------------------------------------------------
// ANIMAL MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";
import {
  SPECIES,
  AGE_UNIT,
  HEALTH,
  SIZE,
  ACTIVITY_LEVEL,
} from "./enums/animal.enums";
import type {
  Species,
  AgeUnit,
  Health,
  Size,
  ActivityLevel,
} from "./enums/animal.enums";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * AnimalAttributes - The complete shape of a Animal record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 * - Optional fields (with ?) can be null/undefined
 */
interface AnimalAttributes {
  id: number; // Primary-Key
  species: Species; // Controlled vocabulary
  name: string; // Name of the animal
  age: number; // Age in units defined below
  ageUnit: AgeUnit; // Age unit
  health: Health; // Controlled health status
  size: Size; // ML Feature
  activityLevel: ActivityLevel; // ML Feature
  goodWithKids: boolean; // ML Feature
  goodWithPets: boolean; // ML Feature
  description?: string | null; // Optional detailed description
  pictureUrl?: string | null; //Optional detail description
  shelterId: number; // Foreign Key
}

/**
 * AnimalCreationAttributes - What is needed to create a animal
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'AnimalAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a animal:
 * - id is auto-generated by a database
 * -
 */
interface AnimalCreationAttributes extends Optional<
  AnimalAttributes,
  "id" | "description" | "pictureUrl"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - The animal model definitions
// -----------------------------------------------------------------
/**
 * The animal class extends Sequelize's model class with the custom types.
 *
 * The generics <AnimalAttributes, AnimalCreationAttributes> tells Sequelize:
 * - When querying, expect AnimalAttribute shape
 * - When creating, allow AnimalCreationAttributes shape
 *
 * Implements AnimalAttributes ensure the class has all required fields
 */
class Animal
  extends Model<AnimalAttributes, AnimalCreationAttributes>
  implements AnimalAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  // the (?) tells Typescript that this is optional entry
  public id!: number;
  public species!: Species;
  public name!: string;
  public age!: number;
  public ageUnit!: AgeUnit;
  public health!: Health;
  public size!: Size;
  public activityLevel!: ActivityLevel;
  public goodWithKids!: boolean;
  public goodWithPets!: boolean;
  public description!: string | null;
  public pictureUrl!: string | null;
  public shelterId!: number;

  // --------------------------------------------
  // Timestamps (automatically managed)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */
  // An Animal can have many adoption requests
  // The foreign key "animalId" will be added to the adoption request table
  static associate(models: Models) {
    Animal.hasMany(models.AdoptionRequest, {
      foreignKey: "animalId",
      onDelete: "SET NULL",
    });

    // An animal belongs to one shelter
    // This adds a shelterId column to animal table
    Animal.belongsTo(models.Shelter, {
      foreignKey: "shelterId",
      onDelete: "CASCADE",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured Animal model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured Animal model class
 */
export default (sequelize: Sequelize) => {
  // Initialize the model with it's schema
  Animal.init(
    {
      // Define all columns with their:
      // - Data types
      // - Constraints (allowNull, unique, etc...)
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      species: {
        type: DataTypes.ENUM(...SPECIES),
        allowNull: false,
      },
      name: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      age: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      ageUnit: {
        type: DataTypes.ENUM(...AGE_UNIT),
        defaultValue: "Years",
        allowNull: false,
        field: "age_unit",
      },
      health: {
        type: DataTypes.ENUM(...HEALTH),
        allowNull: false,
      },
      size: {
        type: DataTypes.ENUM(...SIZE),
        allowNull: false,
      },
      activityLevel: {
        type: DataTypes.ENUM(...ACTIVITY_LEVEL),
        allowNull: false,
        field: "activity_level",
      },
      goodWithKids: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
        field: "good_with_kids",
      },
      goodWithPets: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
        field: "good_with_pets",
      },
      description: {
        type: DataTypes.TEXT,
        allowNull: true,
      },
      pictureUrl: {
        type: DataTypes.STRING,
        allowNull: true,
        field: "picture_url",
      },
      shelterId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "shelter_id",
        references: { model: "Shelter", key: "id" },
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
      },
    },
    {
      sequelize,
      modelName: "Animal", // Sequelize internal model name
      tableName: "animals", // Actual database table
    },
  );

  return Animal;
};

export { Animal };
