// -----------------------------------------------------------------
// COMMENT MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";
// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * CommentAttributes - The complete shape of a Comment record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 */
interface CommentAttributes {
  id: number; // Primary key (auto-generated)
  commentBody: string; // Text content of the comment
  userId: number; // Foreign key -> Users table
  postId: number; // Foreign key -> Posts table
}

/**
 * CommentCreationAttributes - What is needed to create a comment resource
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'CommentAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a county:
 * - id is auto-generated by a database
 * -
 */
interface CommentCreationAttributes extends Optional<CommentAttributes, "id"> {}

// -----------------------------------------------------------------
// MODEL CLASS - The Comment model definitions
// -----------------------------------------------------------------
/**
 * The comment class extends Sequelize's model class with the custom types.
 *
 * The generics <CommentAttributes, CommentCreationAttributes> tells Sequelize:
 * - When querying, expect CommentAttribute shape
 * - When creating, allow CommentCreationAttributes shape
 *
 * Implements CommentAttributes ensure the class has all required fields
 */
class Comment
  extends Model<CommentAttributes, CommentCreationAttributes>
  implements CommentAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  public id!: number;
  public commentBody!: string;
  public userId!: number;
  public postId!: number;

  // --------------------------------------------
  // Timestamps (automatically managed)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */
  static associate(models: Models) {
    // Comment can have many Likes
    Comment.hasMany(models.Like, {
      foreignKey: "commentId",
      onDelete: "CASCADE",
    });

    // Comment belongs to one User
    Comment.belongsTo(models.User, {
      foreignKey: "userId",
      onDelete: "CASCADE",
    });

    // Comment belongs to one Post
    Comment.belongsTo(models.Post, {
      foreignKey: "postId",
      onDelete: "CASCADE",
    });
  }
}

// ----------------------------------------------
// Model Initializer
// ----------------------------------------------
export default (sequelize: Sequelize) => {
  Comment.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      commentBody: {
        type: DataTypes.TEXT,
        allowNull: false,
        field: "comment_body",
      },
      userId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "user_id",
        references: { model: "User", key: "id" },
      },
      postId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "post_id",
        references: { model: "Post", key: "id" },
      },
    },
    {
      sequelize,
      modelName: "Comment", // Internal Sequelize name
      tableName: "comments", // DB table name
    },
  );

  return Comment;
};

export { Comment };
