// -----------------------------------------------------------------
// COUNTY MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * CountyAttributes - The complete shape of a County record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 */
interface CountyAttributes {
  id: number; // Auto-generated primary key
  countyName: string; // Name of the county (Dublin, Cork...)
}

/**
 * CountyCreationAttributes - What is needed to create a county
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'CountyAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a county:
 * - id is auto-generated by a database
 * -
 */
interface CountyCreationAttributes extends Optional<CountyAttributes, "id"> {}

// -----------------------------------------------------------------
// MODEL CLASS - The county model definitions
// -----------------------------------------------------------------
/**
 * The county class extends Sequelize's model class with the custom types.
 *
 * The generics <CountyAttributes, CountyCreationAttributes> tells Sequelize:
 * - When querying, expect CountyAttribute shape
 * - When creating, allow CountyCreationAttributes shape
 *
 * Implements CountyAttributes ensure the class has all required fields
 */
class County
  extends Model<CountyAttributes, CountyCreationAttributes>
  implements CountyAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  public id!: number;
  public countyName!: string;

  // --------------------------------------------
  // Timestamps (automatically managed)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */
  // Counties can have multiple Users and Shelters
  static associate(models: Models) {
    // Each county can have many Users
    County.hasMany(models.User, {
      foreignKey: "countyId",
      onDelete: "SET NULL",
    });
    // Each county can have many shelters
    County.hasMany(models.Shelter, {
      foreignKey: "countyId",
      onDelete: "SET NULL",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured county model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured county model class
 */
export default (sequelize: Sequelize) => {
  County.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      countyName: {
        type: DataTypes.STRING,
        allowNull: false,
        field: "county_name",
        unique: true, // ensures no duplicate county names
      },
    },
    {
      sequelize,
      modelName: "County", // internal Sequelize model name
      tableName: "counties", // table name in DB
    },
  );
  return County;
};

export { County };
