// -----------------------------------------------------------------
// LIKE MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * PostAttributes - The complete shape of a Like record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 * - Optional fields (with ?) can be null/undefined
 */
interface LikeAttributes {
  id: number; // Primary key (auto-generated)
  userId: number; // FK -> Users table (who liked)
  postId?: number | null; // FK -> Posts table (what post was liked)
  commentId?: number | null; // FK -> Comments table (what comment was liked)
}

/**
 * LikeCreationAttributes - What is needed to create a like resource
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'LikeAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a like:
 * - id is auto-generated by a database
 * -
 * -
 */
interface LikeCreationAttributes extends Optional<
  LikeAttributes,
  "id" | "postId" | "commentId"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - Like model definitions
// -----------------------------------------------------------------
/**
 * The like class extends Sequelize's model class with the custom types.
 *
 * The generics <LikeAttributes, LikeCreationAttributes> tells Sequelize:
 * - When querying, expect LikeAttribute shape
 * - When creating, allow LikeCreationAttributes shape
 *
 * Implements LikeAttributes ensure the class has all required fields
 */
class Like
  extends Model<LikeAttributes, LikeCreationAttributes>
  implements LikeAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  // the (?) tells Typescript that this is optional entry
  public id!: number;
  public userId!: number;
  public postId!: number | null;
  public commentId?: number | null;

  // --------------------------------------------
  // Timestamps (automatically managed)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */
  static associate(models: Models) {
    // Like belongs to one User
    Like.belongsTo(models.User, {
      foreignKey: "userId",
      onDelete: "CASCADE",
    });

    // Like belongs to one Post
    Like.belongsTo(models.Post, {
      foreignKey: "postId",
      onDelete: "CASCADE",
    });

    // Like belongs to one Comment
    Like.belongsTo(models.Comment, {
      foreignKey: "commentId",
      onDelete: "CASCADE",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured Post model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured Like model class
 */
export default (sequelize: Sequelize) => {
  Like.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      userId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "user_id",
        references: { model: "users", key: "id" },
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
      },
      postId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: "post_id",
        references: { model: "posts", key: "id" },
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
      },
      commentId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: "comment_id",
        references: { model: "comments", key: "id" },
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
      },
    },
    {
      sequelize,
      modelName: "Like", // Internal Sequelize name
      tableName: "likes", // DB table name
      indexes: [
        {
          unique: true,
          fields: ["user_id", "post_id"], // prevent multiple likes by same user on same post
        },
        {
          unique: true,
          fields: ["user_id", "comment_id"], // prevent multiple likes by same user on same comment
        },
      ],
    },
  );

  return Like;
};

export { Like };
