// -----------------------------------------------------------------
// USER MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * MessageAttributes - The complete shape of a Message record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 * - Optional fields (with ?) can be null/undefined
 */
interface MessageAttribute {
  id: number;
  senderId: number; // FK -> Users or Shelter
  receiverId: number; // FK -> Users or Shelter
  animalId?: number; // optional, tie to specific animal if relevant
  content: string;
  readStatus: boolean; // false = unread, true = read
}

/**
 * MessageCreationAttributes - What is needed to create a message resource
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'MessageAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a message:
 * - id is auto-generated by a database
 * -
 * -
 */
interface MessageCreationAttribute extends Optional<
  MessageAttribute,
  "id" | "readStatus"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - Message model definitions
// -----------------------------------------------------------------
/**
 * The message class extends Sequelize's model class with the custom types.
 *
 * The generics <MessageAttributes, MessageCreationAttributes> tells Sequelize:
 * - When querying, expect MessageAttribute shape
 * - When creating, allow MessageCreationAttributes shape
 *
 * Implements MessageAttributes ensure the class has all required fields
 */
class Message
  extends Model<MessageAttribute, MessageCreationAttribute>
  implements MessageAttribute
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  // the (?) tells Typescript that this is optional entry
  public id!: number;
  public senderId!: number;
  public receiverId!: number;
  public animalId?: number;
  public content!: string;
  public readStatus!: boolean;

  // --------------------------------------------
  // Timestamps (automatically managed)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */

  // Message belongs to one User
  // Sender association
  static associate(models: Models) {
    Message.belongsTo(models.User, {
      foreignKey: "senderId",
      onDelete: "CASCADE",
      onUpdate: "CASCADE",
    });

    // Message belongs to one User
    // Receiver association
    Message.belongsTo(models.User, {
      foreignKey: "receiverId",
      onDelete: "CASCADE",
    });
    // If animalId exists, link message to Animal
    Message.belongsTo(models.Animal, {
      foreignKey: "animalId",
      onDelete: "SET NULL",
      onUpdate: "CASCADE",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured message model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured message model class
 */
export default (sequelize: Sequelize) => {
  Message.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      senderId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "sender_id",
        references: {
          model: "User",
          key: "id",
        },
      },
      receiverId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "receiver_id",
        references: {
          model: "User",
          key: "id",
        },
      },
      animalId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: "animal_id",
        references: {
          model: "Animal",
          key: "id",
        },
      },
      content: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      readStatus: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        field: "read_status",
        defaultValue: false,
      },
    },
    {
      sequelize,
      modelName: "Message",
      tableName: "messages",
    },
  );

  return Message;
};

export { Message };
