// -----------------------------------------------------------------
// POST MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";
import { TYPE } from "./enums/post.enums";
import type { Type } from "./enums/post.enums";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * PostAttributes - The complete shape of a Post record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 * - Optional fields (with ?) can be null/undefined
 */
interface PostAttributes {
  id: number; // Primary key (auto-generated)
  title: string; // Post title
  postText: string; // Main post content
  picture?: string | null; // Optional picture (URL or base64 string)
  userId: number; // Foreign key -> Users table

  type: Type; // type of post Lost | Found | Sighting
  latitude?: number | null; // GPS Latitude (for lost lost/found pet location)
  longitude?: number | null; // GPS Longitude (for lost/found pet location)
}

/**
 * PostCreationAttributes - What is needed to create a post resource
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'PostAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a post:
 * - id is auto-generated by a database
 * -
 * -
 */
interface PostCreationAttributes extends Optional<
  PostAttributes,
  "id" | "picture" | "latitude" | "longitude"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - Post model definitions
// -----------------------------------------------------------------
/**
 * The post class extends Sequelize's model class with the custom types.
 *
 * The generics <PostAttributes, PostCreationAttributes> tells Sequelize:
 * - When querying, expect PostAttribute shape
 * - When creating, allow PostCreationAttributes shape
 *
 * Implements PostAttributes ensure the class has all required fields
 */
class Post
  extends Model<PostAttributes, PostCreationAttributes>
  implements PostAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  // the (?) tells Typescript that this is optional entry
  public id!: number;
  public title!: string;
  public postText!: string;
  public picture?: string | null;
  public userId!: number;

  public type!: Type;
  public latitude?: number | null;
  public longitude?: number | null;

  // --------------------------------------------
  // Timestamps (automatically managed)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */
  static associate(models: Models) {
    // A Post can have many comments
    Post.hasMany(models.Comment, {
      foreignKey: "postId",
      onDelete: "CASCADE",
    });
    // A Post can have many likes
    Post.hasMany(models.Like, {
      foreignKey: "postId",
      onDelete: "CASCADE",
    });
    // A post belongs to one user
    Post.belongsTo(models.User, {
      foreignKey: "userId",
      onDelete: "CASCADE",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured Post model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured Post model class
 */
export default (sequelize: Sequelize) => {
  Post.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      title: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      postText: {
        type: DataTypes.TEXT,
        allowNull: false,
        field: "post_text",
      },
      userId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        field: "user_id",
        references: { model: "users", key: "id" },
        onDelete: "CASCADE",
        onUpdate: "CASCADE",
      },
      picture: {
        type: DataTypes.STRING,
        allowNull: true,
      },
      type: {
        type: DataTypes.ENUM(...TYPE),
        allowNull: false,
      },
      latitude: {
        type: DataTypes.FLOAT,
        allowNull: true,
      },
      longitude: {
        type: DataTypes.FLOAT,
        allowNull: true,
      },
    },
    {
      sequelize,
      modelName: "Post",
      tableName: "posts",
      indexes: [
        {
          fields: ["latitude", "longitude"], // For geo queries
        },
        {
          fields: ["type"], // For filtering by post type
        },
      ],
    },
  );

  return Post;
};

export { Post };
