import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// ----------------------------------------------
// Shelter Staff Model Attribute Definitions
// ----------------------------------------------
// This interface describes ALL fields that exist
// on a ShelterStaff record in the database.
// ----------------------------------------------
interface ShelterStaffAttributes {
  id: number; // Primary key (auto-generated)
  shelterId: number; // FK to Shelters table
  email: string; // Login/email
  password: string; // Hashed password
  role: "Manager" | "Staff"; // Staff role
  userType: "ShelterStaff"; // Role identifier (Shelter Staff)
  status: "Invited" | "Active" | "Disabled"; // Account status
  inviteExpiresAt?: Date; //Expiration of invitation
}

// ----------------------------------------------
// Creation Attributes
// ----------------------------------------------
// Defines which fields are OPTIONAL when creating
// a new Shelter Staff record.
//
// `id` is auto-generated by the database.
// `userType` is assigned a default value.
// ----------------------------------------------
interface ShelterStaffCreationAttributes extends Optional<
  ShelterStaffAttributes,
  "id" | "userType"
> {}

// ----------------------------------------------
// Shelter Staff Model Class
// ----------------------------------------------
// This class:
// - Maps to the "ShelterStaff" database table
// - Provides type-safe access to ShelterStaff records
// - Enables Sequelize ORM features
// ----------------------------------------------

class ShelterStaff
  extends Model<ShelterStaffAttributes, ShelterStaffCreationAttributes>
  implements ShelterStaffAttributes
{
  public id!: number;
  public shelterId!: number;
  public email!: string;
  public password!: string;
  public role!: "Manager" | "Staff";
  public userType!: "ShelterStaff";
  public status!: "Invited" | "Active" | "Disabled";
  public inviteExpiresAt?: Date;

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // --------------------------------------------
  // Model Associations
  // --------------------------------------------
  // Defines relationships between Shelter Staff and
  // other models in the system.
  //
  // -
  // -
  //
  // Cascade delete ensures related records
  //
  // --------------------------------------------

  static associate(models: any) {
    ShelterStaff.hasMany(models.Posts, {
      foreignKey: "shelterStaffId",
      onDelete: "CASCADE",
    });
    ShelterStaff.hasMany(models.Animals, {
      foreignKey: "shelterStaffId",
      onDelete: "CASCADE",
    });
    ShelterStaff.hasMany(models.AdoptionRequests, {
      foreignKey: "reviewedByStaffId",
      onDelete: "SET NULL",
    });
    ShelterStaff.belongsTo(models.Shelter, {
      foreignKey: "shelterId",
      onDelete: "CASCADE",
    });
  }
}

// ----------------------------------------------
// Model Initializer
// ----------------------------------------------
// This function:
// - Defines database column types
// - Applies constraints and defaults
// - Registers the model with Sequelize
// ----------------------------------------------
export default (sequelize: Sequelize) => {
  ShelterStaff.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      shelterId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: { model: "Shelters", key: "id" },
        field: "shelter_id",
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      role: {
        type: DataTypes.ENUM("Manager", "Staff"),
        allowNull: false,
      },
      userType: {
        type: DataTypes.ENUM("ShelterStaff"),
        allowNull: false,
        defaultValue: "ShelterStaff",
        field: "user_type",
      },
      status: {
        type: DataTypes.ENUM("Invited", "Active", "Disabled"),
        allowNull: false,
        defaultValue: "Invited",
      },
      inviteExpiresAt: {
        type: DataTypes.DATE,
        allowNull: true,
        field: "invite_expires_at",
        defaultValue: () => new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
      },
    },
    {
      sequelize,
      modelName: "ShelterStaff",
      tableName: "shelter_staff",
    },
  );
  return ShelterStaff;
};
