// -----------------------------------------------------------------
// SHELTER STAFF MODEL
// -----------------------------------------------------------------

import { DataTypes, Model, Sequelize, Optional } from "sequelize";

import { STATUS, ROLE } from "./enums/shelterStaff.enums";
import type { Status, Role } from "./enums/shelterStaff.enums";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * ShelterStaffAttributes - The complete shape of a Shelter Staff record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 * - Optional fields (with ?) can be null/undefined
 */
interface ShelterStaffAttributes {
  id: number; // Primary key (auto-generated)
  shelterId: number; // FK to Shelters table
  email: string; // Login/email
  password: string; // Hashed password
  role: Role; // Staff Manager | Staff
  userType: "ShelterStaff"; // Role identifier (Shelter Staff)
  status: Status; // Account status
  inviteExpiresAt?: Date; //Expiration of invitation
}

/**
 * ShelterStaffCreationAttributes - What is needed to create a Shelter Staff
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'ShelterStaffAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a shelter:
 * - id is auto-generated by a database
 * - userType has a default value
 */
interface ShelterStaffCreationAttributes extends Optional<
  ShelterStaffAttributes,
  "id" | "userType"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - The shelter staff model definitions
// -----------------------------------------------------------------
/**
 * The shelter staff class extends Sequelize's model class with the custom types.
 *
 * The generics <ShelterStaffAttributes, ShelterStaffCreationAttributes> tells Sequelize:
 * - When querying, expect ShelterStaffAttribute shape
 * - When creating, allow ShelterStaffCreationAttributes shape
 *
 * Implements ShelterStaffAttributes ensure the class has all required fields
 */

class ShelterStaff
  extends Model<ShelterStaffAttributes, ShelterStaffCreationAttributes>
  implements ShelterStaffAttributes
{
  public id!: number;
  public shelterId!: number;
  public email!: string;
  public password!: string;
  public role!: Role; // Manager | Staff
  public userType!: "ShelterStaff";
  public status!: Status;
  public inviteExpiresAt?: Date;

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */
  static associate(models: Models) {
    // A shelter staff can have many Posts
    // The foreign key "shelterStaffId" will be added to the post table
    ShelterStaff.hasMany(models.Post, {
      foreignKey: "shelterStaffId",
      onDelete: "CASCADE",
    });

    // A shelter staff can have many Animals
    ShelterStaff.hasMany(models.Animal, {
      foreignKey: "shelterStaffId",
      onDelete: "CASCADE",
    });

    // A shelter staff can have many Adoption Requests
    // Needed if a user calls in the Shelter Staff can set up Adoption request on behalf of the user
    ShelterStaff.hasMany(models.AdoptionRequest, {
      foreignKey: "reviewedByStaffId",
      onDelete: "SET NULL",
    });

    // A shelter staff belongs to one Shelter
    ShelterStaff.belongsTo(models.Shelter, {
      foreignKey: "shelterId",
      onDelete: "CASCADE",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured Shelter staff model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured Shelter staff model class
 */
export default (sequelize: Sequelize) => {
  ShelterStaff.init(
    {
      // Define all columns with their:
      // - Data types
      // - Constraints (allowNull, unique, etc...)
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      shelterId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: { model: "Shelter", key: "id" },
        field: "shelter_id",
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
        // Note: Passwords are hashed before storage
      },
      role: {
        type: DataTypes.ENUM(...ROLE),
        allowNull: false,
      },
      userType: {
        type: DataTypes.ENUM("ShelterStaff"),
        allowNull: false,
        defaultValue: "ShelterStaff",
        field: "user_type",
      },
      status: {
        type: DataTypes.ENUM(...STATUS),
        allowNull: false,
        defaultValue: "Invited",
      },
      inviteExpiresAt: {
        type: DataTypes.DATE,
        allowNull: true,
        field: "invite_expires_at",
        defaultValue: () => new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
      },
    },
    {
      sequelize,
      modelName: "ShelterStaff",
      tableName: "shelter_staff",
    },
  );
  return ShelterStaff;
};

export { ShelterStaff };
