// -----------------------------------------------------------------
// SHELTER MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";

import { STATUS } from "./enums/shelter.enums";
import type { Status } from "./enums/shelter.enums";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * ShelterAttributes - The complete shape of a Shelter record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 * - Optional fields (with ?) can be null/undefined
 */
interface ShelterAttributes {
  // Core fields
  id: number; // Primary key (auto-generated)
  username: string; // Login username
  password: string; // Hashed password
  email: string; // Contact email
  shelterName: string; // Public name of the shelter
  countyId: number; // Foreign key -> Counties table
  address: string; // Physical address
  phoneNumber: string; // Contact phone
  userType: "Shelter"; // Role identifier, default: "Shelter"
  status: Status;
  verifiedByAdminId?: number; // Optional foreign key
}

/**
 * ShelterCreationAttributes - What is needed to create a shelter
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'ShelterAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a shelter:
 * - id is auto-generated by a database
 * - userType has a default value
 * - verified by admin will occour later as validation is submitted
 */
interface ShelterCreationAttributes extends Optional<
  ShelterAttributes,
  "id" | "userType" | "verifiedByAdminId"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - The shelter model definitions
// -----------------------------------------------------------------
/**
 * The shelter class extends Sequelize's model class with the custom types.
 *
 * The generics <ShelterAttributes, ShelterCreationAttributes> tells Sequelize:
 * - When querying, expect ShelterAttribute shape
 * - When creating, allow ShelterCreationAttributes shape
 *
 * Implements ShelterAttributes ensure the class has all required fields
 */
class Shelter
  extends Model<ShelterAttributes, ShelterCreationAttributes>
  implements ShelterAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  // the (?) tells Typescript that this is optional entry
  public id!: number;
  public username!: string;
  public password!: string;
  public email!: string;
  public shelterName!: string;
  public countyId!: number;
  public address!: string;
  public phoneNumber!: string;
  public userType!: "Shelter";
  public status!: Status;
  public verifiedByAdminId?: number; // Optional foreign key

  // --------------------------------------------
  // Timestamps (automatically managed)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */
  static associate(models: Models) {
    // A shelter can have many likes
    // The foreign key "shelterId" will be added to the post table
    Shelter.hasMany(models.Like, {
      foreignKey: "shelterId",
      onDelete: "CASCADE",
    });

    // A shelter can have many Posts
    Shelter.hasMany(models.Post, {
      foreignKey: "shelterId",
      onDelete: "CASCADE",
    });

    // A shelter can have many Animals
    Shelter.hasMany(models.Animal, {
      foreignKey: "shelterId",
      onDelete: "CASCADE",
    });

    // A shelter can have many Shelter Staff
    Shelter.hasMany(models.ShelterStaff, {
      foreignKey: "shelterId",
      onDelete: "SET NULL",
    });

    // A shelter belongs to one County
    Shelter.belongsTo(models.County, {
      foreignKey: "countyId",
      onDelete: "CASCADE",
    });

    // A shelter belongs to one Admin
    Shelter.belongsTo(models.Admin, {
      foreignKey: "verifiedByAdminId",
      onDelete: "SET NULL",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured Shelter model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured Shelter model class
 */
export default (sequelize: Sequelize) => {
  // Initialize the model with it's schema
  Shelter.init(
    {
      // Define all columns with their:
      // - Data types
      // - Constraints (allowNull, unique, etc...)
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      shelterName: {
        type: DataTypes.STRING,
        allowNull: false,
        field: "shelter_name",
      },
      // Foreign Key county table
      countyId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: { model: "County", key: "id" },
        field: "county_id",
      },
      address: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      phoneNumber: {
        type: DataTypes.STRING(20),
        allowNull: false,
        field: "phone_number",
      },
      userType: {
        type: DataTypes.ENUM("Shelter"),
        defaultValue: "Shelter",
        allowNull: false,
        field: "user_type",
      },
      status: {
        type: DataTypes.ENUM(...STATUS),
        defaultValue: "Unverified",
        allowNull: false,
      },
      verifiedByAdminId: {
        type: DataTypes.INTEGER,
        allowNull: true,
        references: { model: "Admins", key: "id" },
        field: "verified_by_admin_id",
      },
    },
    {
      sequelize,
      modelName: "Shelter", // Sequelize internal model name
      tableName: "shelters", // Actual database table name
    },
  );
  return Shelter;
};

export { Shelter };
