// -----------------------------------------------------------------
// SUPER ADMIN MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * SuperAdminAttributes - The complete shape of a Super Admin record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 */
interface SuperAdminAttributes {
  id: number; // Primary key (auto-generated)
  username: string; // Super Admin login username
  password: string; // Hashed password
  email: string; // Contact email
  userType: "SuperAdmin"; // Role identifier (Super Admin)
}

/**
 * SuperAdminCreationAttributes - What is needed to create a super admin
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'SuperAdminAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a super admin:
 * - id is auto-generated by a database
 * - userType has a default value
 * -
 */
interface SuperAdminCreationAttributes extends Optional<
  SuperAdminAttributes,
  "id" | "userType"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - Super admin model definitions
// -----------------------------------------------------------------
/**
 * The super admin class extends Sequelize's model class with the custom types.
 *
 * The generics <SuperAdminAttributes, SuperAdminCreationAttributes> tells Sequelize:
 * - When querying, expect SuperAdminAttribute shape
 * - When creating, allow SuperAdminCreationAttributes shape
 *
 * Implements SuperAdminAttributes ensure the class has all required fields
 */

class SuperAdmin
  extends Model<SuperAdminAttributes, SuperAdminCreationAttributes>
  implements SuperAdminAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  public id!: number;
  public username!: string;
  public password!: string;
  public email!: string;
  public userType!: "SuperAdmin";

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */

  static associate(models: Models) {
    // Super Admin can have many admins
    SuperAdmin.hasMany(models.Admin, {
      foreignKey: "createdBySuperAdminId",
      onDelete: "SET NULL",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured Super Admin model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured Admin model class
 */
export default (sequelize: Sequelize) => {
  SuperAdmin.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
        // Note: Password is hashed before storage
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      userType: {
        type: DataTypes.ENUM("SuperAdmin"),
        allowNull: false,
        field: "user_type",
        defaultValue: "SuperAdmin",
      },
    },
    {
      sequelize,
      modelName: "SuperAdmin", // Sequelize internal model name
      tableName: "super_admins", // Actual database table name
    },
  );
  return SuperAdmin;
};
export { SuperAdmin };
