import { DataTypes, Model, Sequelize, Optional } from "sequelize";

// ----------------------------------------------
// Super Admin Model Attribute Definitions
// ----------------------------------------------
// This interface describes ALL fields that exist
// on a Super Admin record in the database.
// ----------------------------------------------
interface SuperAdminAttributes {
  id: number; // Primary key (auto-generated)
  username: string; // Super Admin login username
  password: string; // Hashed password
  email: string; // Contact email
  age: number; // Super Admin age
  userType: "SuperAdmin"; // Role identifier (Super Admin)
}

// ----------------------------------------------
// Creation Attributes
// ----------------------------------------------
// Defines which fields are OPTIONAL when creating
// a new Super Admin record.
//
// `id` is auto-generated by the database.
// `userType` is assigned a default value.
// ----------------------------------------------
interface SuperAdminCreationAttributes extends Optional<
  SuperAdminAttributes,
  "id" | "userType"
> {}

// ----------------------------------------------
// Super Admin Model Class
// ----------------------------------------------
// This class:
// - Maps to the "SuperAdmins" database table
// - Provides type-safe access to Super Admin records
// - Enables Sequelize ORM features
// ----------------------------------------------

class SuperAdmin
  extends Model<SuperAdminAttributes, SuperAdminCreationAttributes>
  implements SuperAdminAttributes
{
  public id!: number;
  public username!: string;
  public password!: string;
  public email!: string;
  public age!: number;
  public userType!: "SuperAdmin";

  // --------------------------------------------
  // Timestamps (managed automatically by Sequelize)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // --------------------------------------------
  // Model Associations
  // --------------------------------------------
  // Defines relationships between SuperAdmins and
  // other models in the system.
  //
  // - Super Admin can create many Posts
  // - Super Admin can manage many Counties
  //
  // Cascade delete ensures related records
  // are removed if an Admin is deleted.
  // --------------------------------------------

  static associate(models: any) {
    SuperAdmin.hasMany(models.Post, { onDelete: "cascade" });
    SuperAdmin.hasMany(models.County, { onDelete: "cascade" });
    SuperAdmin.hasMany(models.Admin, { onDelete: "SET NULL" });
  }
}

// ----------------------------------------------
// Model Initializer
// ----------------------------------------------
// This function:
// - Defines database column types
// - Applies constraints and defaults
// - Registers the model with Sequelize
// ----------------------------------------------
export default (sequelize: Sequelize) => {
  SuperAdmin.init(
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
      },
      age: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      userType: {
        type: DataTypes.ENUM("SuperAdmin"),
        allowNull: false,
        field: "user_type",
        defaultValue: "SuperAdmin",
      },
    },
    {
      sequelize,
      modelName: "SuperAdmin", // Sequelize internal model name
      tableName: "super_admins", // Actual database table name
    },
  );
  return SuperAdmin;
};
