// -----------------------------------------------------------------
// USER MODEL
// -----------------------------------------------------------------
import { DataTypes, Model, Sequelize, Optional } from "sequelize";
import {
  ACTIVITY_LEVELS,
  PET_EXPERIENCE_LEVELS,
  DOG_SIZES,
} from "./enums/user.enums";
import type {
  ActivityLevel,
  PetExperienceLevel,
  DogSize,
} from "./enums/user.enums";

// Import the Model interfaces from the central registry
// This allows type safety for associations
import type { Models } from "./index";

// -----------------------------------------------------------------
// INTERFACE - Defining data shapes
// -----------------------------------------------------------------
/**
 * UserAttributes - The complete shape of a User record
 *
 * This interface describes every field that exists in the database.
 * A database schema in TypeScript form
 * - Required fields must be present
 * - Optional fields (with ?) can be null/undefined
 */
interface UserAttributes {
  // Core fields
  id: number; // Auto-generated primary key
  username: string; // Unique username
  password: string; // Hashed password
  email: string; // Unique email
  age: number; // User's age
  userType: "User"; // User role

  // Foreign Keys
  countyId?: number; // User's county

  // Matching preferences (for dog adoption)
  activityLevel: ActivityLevel; // How active they are
  hasGarden: boolean; // Do they have a garden?
  hasOtherPets: boolean; // Do they have other pets?
  hasKids: boolean; // Do they have children?
  petExperienceLevel: PetExperienceLevel; // Experience with pets
  maxDogSize: DogSize; // Biggest dog they can handle

  // Optional preferences
  preferredEnergyLevel?: ActivityLevel;
  preferredAgeRangeMin?: number;
  preferredAgeRangeMax?: number;
}

/**
 * UserCreationAttributes - What is needed to create a user
 *
 * This extends Optional<T, K> which is a TypeScript utility that says:
 * Take 'UserAttributes', but make these specific fields optional during creation.
 *
 * Why? when creating a user:
 * - id is auto-generated by a database
 * - userType has a default value
 * - preferenes can be set later
 */
interface UserCreationAttributes extends Optional<
  UserAttributes,
  | "id"
  | "userType"
  | "countyId"
  | "preferredEnergyLevel"
  | "preferredAgeRangeMin"
  | "preferredAgeRangeMax"
> {}

// -----------------------------------------------------------------
// MODEL CLASS - The user model definitions
// -----------------------------------------------------------------
/**
 * The user class extends Sequelize's model class with the custom types.
 *
 * The generics <UserAttributes, UserCreationAttributes> tells Sequelize:
 * - When querying, expect UserAttribute shape
 * - When creating, allow UserCreationAttributes shape
 *
 * Implements UserAttributes ensure the class has all required fields
 */
class User
  extends Model<UserAttributes, UserCreationAttributes>
  implements UserAttributes
{
  // All fields must be declared as class properties
  // The (!) tells TypeScript this will be initialized by Sequelize - trust me bro!
  public id!: number;
  public username!: string;
  public password!: string;
  public email!: string;
  public age!: number;
  public userType!: "User";
  public countyId?: number;
  public activityLevel!: ActivityLevel;
  public hasGarden!: boolean;
  public hasOtherPets!: boolean;
  public hasKids!: boolean;
  public petExperienceLevel!: PetExperienceLevel;
  public maxDogSize!: DogSize;
  public preferredEnergyLevel?: ActivityLevel;
  public preferredAgeRangeMin?: number;
  public preferredAgeRangeMax?: number;

  // --------------------------------------------
  // Timestamps (automatically managed)
  // --------------------------------------------
  public readonly createdAt!: Date;
  public readonly updatedAt!: Date;

  // -----------------------------------------------------------------
  // ASSOCIATIONS - Relationships between models
  // -----------------------------------------------------------------
  /**
   * The associate method connects this model to others.
   *
   * NOTICE: It now uses the Models interface instead of 'any'!
   * This means:
   * - Typescript knows exactly what models exist
   * - Autocomplete shows only valid models
   * - Error thrown if attempted to access a model that does not exist
   *
   * @param models - The complete registry of all models
   */
  static associate(models: Models) {
    // A user can have many Posts
    // The foreign key "userId" will be added to the post table
    User.hasMany(models.Post, {
      foreignKey: "userId", // Column name in post table
      onDelete: "CASCADE", // If User is deleted, delete their posts
    });

    // A user can have many Comments
    User.hasMany(models.Comment, {
      foreignKey: "userId",
      onDelete: "CASCADE",
    });

    // A user can have many Likes
    User.hasMany(models.Like, {
      foreignKey: "userId",
      onDelete: "CASCADE",
    });

    // A user can send many Adoption Requests
    User.hasMany(models.AdoptionRequest, {
      foreignKey: "userId",
    });

    // A user belongs to one County
    // This adds a countyId column to User table
    User.belongsTo(models.County, {
      foreignKey: "countyId",
    });
  }
}

// -----------------------------------------------------------------
// MODEL INITIALIZER - The factory function
// -----------------------------------------------------------------
/**
 * This is the default export function - the Initializer or factory
 *
 * It takes a Sequelize instance and returns a configured User model class.
 *
 * @param sequelize - The Sequelize database connection
 * @returns The configured User model class
 */
export default (sequelize: Sequelize) => {
  // Initialize the model with it's schema
  User.init(
    {
      // Define all columns with their:
      // - Data types
      // - Constraints (allowNull, unique, etc...)
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      username: {
        type: DataTypes.STRING,
        allowNull: false, // Must include username
        unique: true, // Must be unique
        validate: {
          notEmpty: true, // Cannot be empty string
          len: [3, 30], // Between 3 and 30 characters
        },
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false,
        // Note: no validation here - passwords are hashed
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false, // Must include email
        unique: true, // Must be unique
        validate: {
          isEmail: true, // Must be valid email format
          notEmpty: true,
        },
      },
      age: {
        type: DataTypes.INTEGER,
        allowNull: false,
        validate: {
          min: 0, // Can't be negative
          max: 100, // maximum age limit
        },
      },

      // Foreign Key county table
      countyId: {
        type: DataTypes.INTEGER,
        allowNull: true, // Optional
        field: "county_id", // Mapping to DB == Column name (snake_case)
        references: {
          model: "County", // References County table
          key: "id", // References County.id column
        },
      },

      userType: {
        type: DataTypes.ENUM("User"),
        defaultValue: "User",
        allowNull: false,
        field: "user_type",
      },

      activityLevel: {
        type: DataTypes.ENUM(...ACTIVITY_LEVELS),
        allowNull: false,
        field: "activity_level",
      },

      hasGarden: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        field: "has_garden",
      },

      hasOtherPets: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        field: "has_other_pets",
      },

      hasKids: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        field: "has_kids",
      },

      petExperienceLevel: {
        type: DataTypes.ENUM(...PET_EXPERIENCE_LEVELS),
        allowNull: false,
        field: "pet_experience_level",
      },

      maxDogSize: {
        type: DataTypes.ENUM(...DOG_SIZES),
        allowNull: false,
        field: "max_dog_size",
      },

      preferredEnergyLevel: {
        type: DataTypes.ENUM(...ACTIVITY_LEVELS),
        allowNull: true,
        field: "preferred_energy_level",
      },

      preferredAgeRangeMin: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: "preferred_age_range_min",
      },

      preferredAgeRangeMax: {
        type: DataTypes.INTEGER,
        allowNull: true,
        field: "preferred_age_range_max",
      },
    },
    {
      sequelize,
      modelName: "User",
      tableName: "users",
    },
  );

  // Return the configured model class
  return User;
};
// Export the class type for use in otherfiles
export { User };
